# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 100 exercises with qsv
author: "<a href='https://dathere.com'>datHere</a> and <a href='https://github.com/dathere/100.dathere.com/graphs/contributors'>contributors</a>."
logo: media/qsv-logo.png
exclude_patterns:
    [
        "README.md",
        ".venv",
        ".vscode",
        ".gitignore",
        "postBuild",
        "requirements*.txt",
        "bash_kernel",
    ]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
    execute_notebooks: force

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
    use_repository_button: true
    favicon: media/qsv-logo-dark-icon.png
    extra_footer: |
        <p>
        © Copyright datHere
        </p>

# Information about where the book exists on the web
repository:
    url: https://github.com/dathere/100.dathere.com # Online location of your book
    branch: main # Which branch of the repository should be used when creating links (optional)
launch_buttons:
    notebook_interface: jupyterlab
    binderhub_url: https://mybinder.org
    thebe: true
sphinx:
    config:
        html_show_copyright: false
        html_theme_options:
            logo:
                image_light: media/qsv-logo.png
                image_dark: media/qsv-logo-dark.png
    recursive_update: true
    language: en
