#!/bin/bash

set -ex

pip install bash_kernel
python -m bash_kernel.install

rm -rf path_files
mkdir path_files
export PATH=/home/jovyan/path_files:$PATH
cd path_files
curl -LO https://github.com/jqnatividad/qsv/releases/download/0.128.0/qsv-0.128.0-x86_64-unknown-linux-gnu.zip
unzip qsv-0.128.0-x86_64-unknown-linux-gnu.zip
rm qsv*
cd ..